name: flutter-build
on: [push]
permissions:
  contents: write
  pull-requests: write
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version-file: pubspec.yaml # path to pubspec.yaml
    - run: flutter --version
    - run: flutter pub get
    - run: flutter build web
      
    - name: Pushes test folder
      uses: datalbry/copy_folder_to_another_repo_action@1.0.0
      env:
        API_TOKEN_GITHUB: ${{ secrets.IO_REPO_ACCESS_TOKEN }}
      with:
        source_folder: 'build/web'
        destination_repo: 'kimhanil-dev/kimhanil-dev.github.io'
        user_email: 'khlj752@naver.com'
        user_name: 'kimhanil-dev'
        destination_branch: 'main'
        commit_msg: '[GHA] Update the test files.'
