name: flutter-build
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version-file: pubspec.yaml # path to pubspec.yaml
    - run: flutter --version
    - run: flutter pub get
    - run: flutter build web
      
    
    - name: Set up Git
      run: |
        git config --global user.name 'kimhanil-dev'
        git config --global user.email 'khlj752@naver.com'
    
    - name: Add destination repository  as a remote
      run: sudo cd ./build/web
    - run: git remote add build https://kimhan-dev:${{ secrets.GH_TOKEN }}@github.com/kimhanil-dev/kimhanil-dev.github.io.git
    
    - name: Push to kimhanil-dev.github.io
      run: sudo cd ./build/web
    - run: git push origin main
        
