name: flutter-build
on: [push]
jobs:
  check-bats-version:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version-file: pubspec.yaml # path to pubspec.yaml
    - run: flutter --version
    - run: flutter pub get
    - run: flutter build web

    - run: |
        git init
        git config user.email "khlj752@naver.com"
        git config user.name "kimhanil-dev"
        git clone --branch main https://kimhanil-dev:${{ secrets.GH_TOKEN }}@github.com/kimhanil-dev/kimhanil-dev.github.io.git
        git add .
        git commit -m "Build"
        git push https://kimhanil-dev:${{ secrets.GH_TOKEN }}@github.com/kimhanil-dev/kimhanil-dev.github.io.git main
